@startuml
package demy-platform-backend as demy_platform_backend  {
    package enrollments {
        package domain {}
        package infrastructure {}
        package application {}
        package interfaces {}
    }
'    package iam {}
'    package scheduling {}
'    package billing {}
'    package attendance {}
'    package shared {}
}
package org.springframework.data.domain {}
package org.hibernate.boot.model.naming {}

demy_platform_backend.enrollments.domain ..> org.springframework.data.domain
demy_platform_backend.enrollments.infrastructure ..> demy_platform_backend.enrollments.domain
demy_platform_backend.enrollments.application ..> demy_platform_backend.enrollments.domain
demy_platform_backend.enrollments.application ..> demy_platform_backend.enrollments.infrastructure
demy_platform_backend.enrollments.interfaces ..> demy_platform_backend.enrollments.application
demy_platform_backend.enrollments.interfaces ..> demy_platform_backend.enrollments.domain
demy_platform_backend.shared.interfaces ..> org.hibernate.boot.model.naming


@enduml